/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MealPlansRouteImport } from './routes/meal-plans'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealPlansIdRouteImport } from './routes/meal-plans.$id'
import { Route as DishIdRouteImport } from './routes/dish.$id'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMySubscriptionsRouteImport } from './routes/_authenticated/my-subscriptions'
import { Route as AuthenticatedDeliveryRouteImport } from './routes/_authenticated/delivery'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedBecomeSellerRouteImport } from './routes/_authenticated/become-seller'
import { Route as AuthenticatedAddressesRouteImport } from './routes/_authenticated/addresses'
import { Route as AuthenticatedSellerRouteRouteImport } from './routes/_authenticated/seller/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedSellerIndexRouteImport } from './routes/_authenticated/seller/index'
import { Route as AuthenticatedDeliveryIndexRouteImport } from './routes/_authenticated/delivery.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as AuthenticatedSellerSubscriptionsRouteImport } from './routes/_authenticated/seller/subscriptions'
import { Route as AuthenticatedSellerOrdersRouteImport } from './routes/_authenticated/seller/orders'
import { Route as AuthenticatedSellerMealPlansRouteImport } from './routes/_authenticated/seller/meal-plans'
import { Route as AuthenticatedSellerDishesRouteImport } from './routes/_authenticated/seller/dishes'
import { Route as AuthenticatedSellerDeliveryRouteImport } from './routes/_authenticated/seller/delivery'
import { Route as AuthenticatedSellerCouponsRouteImport } from './routes/_authenticated/seller/coupons'
import { Route as AuthenticatedSellerCampaignsRouteImport } from './routes/_authenticated/seller/campaigns'
import { Route as AuthenticatedSellerAnalyticsRouteImport } from './routes/_authenticated/seller/analytics'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedMySubscriptionsIdRouteImport } from './routes/_authenticated/my-subscriptions.$id'
import { Route as AuthenticatedDeliveryRegisterRouteImport } from './routes/_authenticated/delivery.register'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin/subscriptions'
import { Route as AuthenticatedAdminSellersRouteImport } from './routes/_authenticated/admin/sellers'
import { Route as AuthenticatedAdminPromotionsRouteImport } from './routes/_authenticated/admin/promotions'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminDeliveryRouteImport } from './routes/_authenticated/admin/delivery'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin/coupons'
import { Route as AuthenticatedAdminCampaignsRouteImport } from './routes/_authenticated/admin/campaigns'
import { Route as AuthenticatedAdminAbuseRouteImport } from './routes/_authenticated/admin/abuse'
import { Route as AuthenticatedAdminRewardsRouteRouteImport } from './routes/_authenticated/admin/rewards/route'
import { Route as AuthenticatedAdminRewardsIndexRouteImport } from './routes/_authenticated/admin/rewards/index'
import { Route as AuthenticatedAdminRewardsWheelsRouteImport } from './routes/_authenticated/admin/rewards/wheels'
import { Route as AuthenticatedAdminRewardsReferralsRouteImport } from './routes/_authenticated/admin/rewards/referrals'
import { Route as AuthenticatedAdminRewardsAuditRouteImport } from './routes/_authenticated/admin/rewards/audit'
import { Route as AuthenticatedAdminRewardsAnalyticsRouteImport } from './routes/_authenticated/admin/rewards/analytics'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlansRoute = MealPlansRouteImport.update({
  id: '/meal-plans',
  path: '/meal-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlansIdRoute = MealPlansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MealPlansRoute,
} as any)
const DishIdRoute = DishIdRouteImport.update({
  id: '/dish/$id',
  path: '/dish/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMySubscriptionsRoute =
  AuthenticatedMySubscriptionsRouteImport.update({
    id: '/my-subscriptions',
    path: '/my-subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryRoute = AuthenticatedDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBecomeSellerRoute =
  AuthenticatedBecomeSellerRouteImport.update({
    id: '/become-seller',
    path: '/become-seller',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAddressesRoute = AuthenticatedAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerRouteRoute =
  AuthenticatedSellerRouteRouteImport.update({
    id: '/seller',
    path: '/seller',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerIndexRoute =
  AuthenticatedSellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedDeliveryIndexRoute =
  AuthenticatedDeliveryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDeliveryRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSellerSubscriptionsRoute =
  AuthenticatedSellerSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedSellerOrdersRoute =
  AuthenticatedSellerOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedSellerMealPlansRoute =
  AuthenticatedSellerMealPlansRouteImport.update({
    id: '/meal-plans',
    path: '/meal-plans',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedSellerDishesRoute =
  AuthenticatedSellerDishesRouteImport.update({
    id: '/dishes',
    path: '/dishes',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedSellerDeliveryRoute =
  AuthenticatedSellerDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedSellerCouponsRoute =
  AuthenticatedSellerCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedSellerCampaignsRoute =
  AuthenticatedSellerCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedSellerAnalyticsRoute =
  AuthenticatedSellerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOrdersRoute,
} as any)
const AuthenticatedMySubscriptionsIdRoute =
  AuthenticatedMySubscriptionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMySubscriptionsRoute,
  } as any)
const AuthenticatedDeliveryRegisterRoute =
  AuthenticatedDeliveryRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AuthenticatedDeliveryRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSellersRoute =
  AuthenticatedAdminSellersRouteImport.update({
    id: '/sellers',
    path: '/sellers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPromotionsRoute =
  AuthenticatedAdminPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDeliveryRoute =
  AuthenticatedAdminDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCampaignsRoute =
  AuthenticatedAdminCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAbuseRoute = AuthenticatedAdminAbuseRouteImport.update({
  id: '/abuse',
  path: '/abuse',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminRewardsRouteRoute =
  AuthenticatedAdminRewardsRouteRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRewardsIndexRoute =
  AuthenticatedAdminRewardsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminRewardsRouteRoute,
  } as any)
const AuthenticatedAdminRewardsWheelsRoute =
  AuthenticatedAdminRewardsWheelsRouteImport.update({
    id: '/wheels',
    path: '/wheels',
    getParentRoute: () => AuthenticatedAdminRewardsRouteRoute,
  } as any)
const AuthenticatedAdminRewardsReferralsRoute =
  AuthenticatedAdminRewardsReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAdminRewardsRouteRoute,
  } as any)
const AuthenticatedAdminRewardsAuditRoute =
  AuthenticatedAdminRewardsAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedAdminRewardsRouteRoute,
  } as any)
const AuthenticatedAdminRewardsAnalyticsRoute =
  AuthenticatedAdminRewardsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRewardsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/meal-plans': typeof MealPlansRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/seller': typeof AuthenticatedSellerRouteRouteWithChildren
  '/addresses': typeof AuthenticatedAddressesRoute
  '/become-seller': typeof AuthenticatedBecomeSellerRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/delivery': typeof AuthenticatedDeliveryRouteWithChildren
  '/my-subscriptions': typeof AuthenticatedMySubscriptionsRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/rewards': typeof AuthenticatedRewardsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/dish/$id': typeof DishIdRoute
  '/meal-plans/$id': typeof MealPlansIdRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsRouteRouteWithChildren
  '/admin/abuse': typeof AuthenticatedAdminAbuseRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/sellers': typeof AuthenticatedAdminSellersRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/delivery/register': typeof AuthenticatedDeliveryRegisterRoute
  '/my-subscriptions/$id': typeof AuthenticatedMySubscriptionsIdRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/seller/analytics': typeof AuthenticatedSellerAnalyticsRoute
  '/seller/campaigns': typeof AuthenticatedSellerCampaignsRoute
  '/seller/coupons': typeof AuthenticatedSellerCouponsRoute
  '/seller/delivery': typeof AuthenticatedSellerDeliveryRoute
  '/seller/dishes': typeof AuthenticatedSellerDishesRoute
  '/seller/meal-plans': typeof AuthenticatedSellerMealPlansRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/seller/subscriptions': typeof AuthenticatedSellerSubscriptionsRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/delivery/': typeof AuthenticatedDeliveryIndexRoute
  '/seller/': typeof AuthenticatedSellerIndexRoute
  '/admin/rewards/analytics': typeof AuthenticatedAdminRewardsAnalyticsRoute
  '/admin/rewards/audit': typeof AuthenticatedAdminRewardsAuditRoute
  '/admin/rewards/referrals': typeof AuthenticatedAdminRewardsReferralsRoute
  '/admin/rewards/wheels': typeof AuthenticatedAdminRewardsWheelsRoute
  '/admin/rewards/': typeof AuthenticatedAdminRewardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/meal-plans': typeof MealPlansRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/addresses': typeof AuthenticatedAddressesRoute
  '/become-seller': typeof AuthenticatedBecomeSellerRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/my-subscriptions': typeof AuthenticatedMySubscriptionsRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/rewards': typeof AuthenticatedRewardsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/dish/$id': typeof DishIdRoute
  '/meal-plans/$id': typeof MealPlansIdRoute
  '/admin/abuse': typeof AuthenticatedAdminAbuseRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/sellers': typeof AuthenticatedAdminSellersRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/delivery/register': typeof AuthenticatedDeliveryRegisterRoute
  '/my-subscriptions/$id': typeof AuthenticatedMySubscriptionsIdRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/seller/analytics': typeof AuthenticatedSellerAnalyticsRoute
  '/seller/campaigns': typeof AuthenticatedSellerCampaignsRoute
  '/seller/coupons': typeof AuthenticatedSellerCouponsRoute
  '/seller/delivery': typeof AuthenticatedSellerDeliveryRoute
  '/seller/dishes': typeof AuthenticatedSellerDishesRoute
  '/seller/meal-plans': typeof AuthenticatedSellerMealPlansRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/seller/subscriptions': typeof AuthenticatedSellerSubscriptionsRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/delivery': typeof AuthenticatedDeliveryIndexRoute
  '/seller': typeof AuthenticatedSellerIndexRoute
  '/admin/rewards/analytics': typeof AuthenticatedAdminRewardsAnalyticsRoute
  '/admin/rewards/audit': typeof AuthenticatedAdminRewardsAuditRoute
  '/admin/rewards/referrals': typeof AuthenticatedAdminRewardsReferralsRoute
  '/admin/rewards/wheels': typeof AuthenticatedAdminRewardsWheelsRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/meal-plans': typeof MealPlansRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/seller': typeof AuthenticatedSellerRouteRouteWithChildren
  '/_authenticated/addresses': typeof AuthenticatedAddressesRoute
  '/_authenticated/become-seller': typeof AuthenticatedBecomeSellerRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/delivery': typeof AuthenticatedDeliveryRouteWithChildren
  '/_authenticated/my-subscriptions': typeof AuthenticatedMySubscriptionsRouteWithChildren
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/dish/$id': typeof DishIdRoute
  '/meal-plans/$id': typeof MealPlansIdRoute
  '/_authenticated/admin/rewards': typeof AuthenticatedAdminRewardsRouteRouteWithChildren
  '/_authenticated/admin/abuse': typeof AuthenticatedAdminAbuseRoute
  '/_authenticated/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/_authenticated/admin/sellers': typeof AuthenticatedAdminSellersRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/delivery/register': typeof AuthenticatedDeliveryRegisterRoute
  '/_authenticated/my-subscriptions/$id': typeof AuthenticatedMySubscriptionsIdRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/seller/analytics': typeof AuthenticatedSellerAnalyticsRoute
  '/_authenticated/seller/campaigns': typeof AuthenticatedSellerCampaignsRoute
  '/_authenticated/seller/coupons': typeof AuthenticatedSellerCouponsRoute
  '/_authenticated/seller/delivery': typeof AuthenticatedSellerDeliveryRoute
  '/_authenticated/seller/dishes': typeof AuthenticatedSellerDishesRoute
  '/_authenticated/seller/meal-plans': typeof AuthenticatedSellerMealPlansRoute
  '/_authenticated/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/_authenticated/seller/subscriptions': typeof AuthenticatedSellerSubscriptionsRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/delivery/': typeof AuthenticatedDeliveryIndexRoute
  '/_authenticated/seller/': typeof AuthenticatedSellerIndexRoute
  '/_authenticated/admin/rewards/analytics': typeof AuthenticatedAdminRewardsAnalyticsRoute
  '/_authenticated/admin/rewards/audit': typeof AuthenticatedAdminRewardsAuditRoute
  '/_authenticated/admin/rewards/referrals': typeof AuthenticatedAdminRewardsReferralsRoute
  '/_authenticated/admin/rewards/wheels': typeof AuthenticatedAdminRewardsWheelsRoute
  '/_authenticated/admin/rewards/': typeof AuthenticatedAdminRewardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/meal-plans'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/trust'
    | '/admin'
    | '/seller'
    | '/addresses'
    | '/become-seller'
    | '/checkout'
    | '/delivery'
    | '/my-subscriptions'
    | '/orders'
    | '/rewards'
    | '/wishlist'
    | '/dish/$id'
    | '/meal-plans/$id'
    | '/admin/rewards'
    | '/admin/abuse'
    | '/admin/campaigns'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/promotions'
    | '/admin/sellers'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/delivery/register'
    | '/my-subscriptions/$id'
    | '/orders/$id'
    | '/seller/analytics'
    | '/seller/campaigns'
    | '/seller/coupons'
    | '/seller/delivery'
    | '/seller/dishes'
    | '/seller/meal-plans'
    | '/seller/orders'
    | '/seller/subscriptions'
    | '/api/public/razorpay-webhook'
    | '/admin/'
    | '/delivery/'
    | '/seller/'
    | '/admin/rewards/analytics'
    | '/admin/rewards/audit'
    | '/admin/rewards/referrals'
    | '/admin/rewards/wheels'
    | '/admin/rewards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/meal-plans'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/trust'
    | '/addresses'
    | '/become-seller'
    | '/checkout'
    | '/my-subscriptions'
    | '/orders'
    | '/rewards'
    | '/wishlist'
    | '/dish/$id'
    | '/meal-plans/$id'
    | '/admin/abuse'
    | '/admin/campaigns'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/promotions'
    | '/admin/sellers'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/delivery/register'
    | '/my-subscriptions/$id'
    | '/orders/$id'
    | '/seller/analytics'
    | '/seller/campaigns'
    | '/seller/coupons'
    | '/seller/delivery'
    | '/seller/dishes'
    | '/seller/meal-plans'
    | '/seller/orders'
    | '/seller/subscriptions'
    | '/api/public/razorpay-webhook'
    | '/admin'
    | '/delivery'
    | '/seller'
    | '/admin/rewards/analytics'
    | '/admin/rewards/audit'
    | '/admin/rewards/referrals'
    | '/admin/rewards/wheels'
    | '/admin/rewards'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/meal-plans'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/trust'
    | '/_authenticated/admin'
    | '/_authenticated/seller'
    | '/_authenticated/addresses'
    | '/_authenticated/become-seller'
    | '/_authenticated/checkout'
    | '/_authenticated/delivery'
    | '/_authenticated/my-subscriptions'
    | '/_authenticated/orders'
    | '/_authenticated/rewards'
    | '/_authenticated/wishlist'
    | '/dish/$id'
    | '/meal-plans/$id'
    | '/_authenticated/admin/rewards'
    | '/_authenticated/admin/abuse'
    | '/_authenticated/admin/campaigns'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/delivery'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/promotions'
    | '/_authenticated/admin/sellers'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/users'
    | '/_authenticated/delivery/register'
    | '/_authenticated/my-subscriptions/$id'
    | '/_authenticated/orders/$id'
    | '/_authenticated/seller/analytics'
    | '/_authenticated/seller/campaigns'
    | '/_authenticated/seller/coupons'
    | '/_authenticated/seller/delivery'
    | '/_authenticated/seller/dishes'
    | '/_authenticated/seller/meal-plans'
    | '/_authenticated/seller/orders'
    | '/_authenticated/seller/subscriptions'
    | '/api/public/razorpay-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/delivery/'
    | '/_authenticated/seller/'
    | '/_authenticated/admin/rewards/analytics'
    | '/_authenticated/admin/rewards/audit'
    | '/_authenticated/admin/rewards/referrals'
    | '/_authenticated/admin/rewards/wheels'
    | '/_authenticated/admin/rewards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  CartRoute: typeof CartRoute
  MealPlansRoute: typeof MealPlansRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  DishIdRoute: typeof DishIdRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plans': {
      id: '/meal-plans'
      path: '/meal-plans'
      fullPath: '/meal-plans'
      preLoaderRoute: typeof MealPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plans/$id': {
      id: '/meal-plans/$id'
      path: '/$id'
      fullPath: '/meal-plans/$id'
      preLoaderRoute: typeof MealPlansIdRouteImport
      parentRoute: typeof MealPlansRoute
    }
    '/dish/$id': {
      id: '/dish/$id'
      path: '/dish/$id'
      fullPath: '/dish/$id'
      preLoaderRoute: typeof DishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-subscriptions': {
      id: '/_authenticated/my-subscriptions'
      path: '/my-subscriptions'
      fullPath: '/my-subscriptions'
      preLoaderRoute: typeof AuthenticatedMySubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery': {
      id: '/_authenticated/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthenticatedDeliveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/become-seller': {
      id: '/_authenticated/become-seller'
      path: '/become-seller'
      fullPath: '/become-seller'
      preLoaderRoute: typeof AuthenticatedBecomeSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/addresses': {
      id: '/_authenticated/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AuthenticatedAddressesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/': {
      id: '/_authenticated/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof AuthenticatedSellerIndexRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/delivery/': {
      id: '/_authenticated/delivery/'
      path: '/'
      fullPath: '/delivery/'
      preLoaderRoute: typeof AuthenticatedDeliveryIndexRouteImport
      parentRoute: typeof AuthenticatedDeliveryRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seller/subscriptions': {
      id: '/_authenticated/seller/subscriptions'
      path: '/subscriptions'
      fullPath: '/seller/subscriptions'
      preLoaderRoute: typeof AuthenticatedSellerSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/seller/orders': {
      id: '/_authenticated/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof AuthenticatedSellerOrdersRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/seller/meal-plans': {
      id: '/_authenticated/seller/meal-plans'
      path: '/meal-plans'
      fullPath: '/seller/meal-plans'
      preLoaderRoute: typeof AuthenticatedSellerMealPlansRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/seller/dishes': {
      id: '/_authenticated/seller/dishes'
      path: '/dishes'
      fullPath: '/seller/dishes'
      preLoaderRoute: typeof AuthenticatedSellerDishesRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/seller/delivery': {
      id: '/_authenticated/seller/delivery'
      path: '/delivery'
      fullPath: '/seller/delivery'
      preLoaderRoute: typeof AuthenticatedSellerDeliveryRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/seller/coupons': {
      id: '/_authenticated/seller/coupons'
      path: '/coupons'
      fullPath: '/seller/coupons'
      preLoaderRoute: typeof AuthenticatedSellerCouponsRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/seller/campaigns': {
      id: '/_authenticated/seller/campaigns'
      path: '/campaigns'
      fullPath: '/seller/campaigns'
      preLoaderRoute: typeof AuthenticatedSellerCampaignsRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/seller/analytics': {
      id: '/_authenticated/seller/analytics'
      path: '/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof AuthenticatedSellerAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/my-subscriptions/$id': {
      id: '/_authenticated/my-subscriptions/$id'
      path: '/$id'
      fullPath: '/my-subscriptions/$id'
      preLoaderRoute: typeof AuthenticatedMySubscriptionsIdRouteImport
      parentRoute: typeof AuthenticatedMySubscriptionsRoute
    }
    '/_authenticated/delivery/register': {
      id: '/_authenticated/delivery/register'
      path: '/register'
      fullPath: '/delivery/register'
      preLoaderRoute: typeof AuthenticatedDeliveryRegisterRouteImport
      parentRoute: typeof AuthenticatedDeliveryRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sellers': {
      id: '/_authenticated/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AuthenticatedAdminSellersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/promotions': {
      id: '/_authenticated/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AuthenticatedAdminPromotionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/delivery': {
      id: '/_authenticated/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AuthenticatedAdminDeliveryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/campaigns': {
      id: '/_authenticated/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/abuse': {
      id: '/_authenticated/admin/abuse'
      path: '/abuse'
      fullPath: '/admin/abuse'
      preLoaderRoute: typeof AuthenticatedAdminAbuseRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rewards': {
      id: '/_authenticated/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AuthenticatedAdminRewardsRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rewards/': {
      id: '/_authenticated/admin/rewards/'
      path: '/'
      fullPath: '/admin/rewards/'
      preLoaderRoute: typeof AuthenticatedAdminRewardsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRewardsRouteRoute
    }
    '/_authenticated/admin/rewards/wheels': {
      id: '/_authenticated/admin/rewards/wheels'
      path: '/wheels'
      fullPath: '/admin/rewards/wheels'
      preLoaderRoute: typeof AuthenticatedAdminRewardsWheelsRouteImport
      parentRoute: typeof AuthenticatedAdminRewardsRouteRoute
    }
    '/_authenticated/admin/rewards/referrals': {
      id: '/_authenticated/admin/rewards/referrals'
      path: '/referrals'
      fullPath: '/admin/rewards/referrals'
      preLoaderRoute: typeof AuthenticatedAdminRewardsReferralsRouteImport
      parentRoute: typeof AuthenticatedAdminRewardsRouteRoute
    }
    '/_authenticated/admin/rewards/audit': {
      id: '/_authenticated/admin/rewards/audit'
      path: '/audit'
      fullPath: '/admin/rewards/audit'
      preLoaderRoute: typeof AuthenticatedAdminRewardsAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRewardsRouteRoute
    }
    '/_authenticated/admin/rewards/analytics': {
      id: '/_authenticated/admin/rewards/analytics'
      path: '/analytics'
      fullPath: '/admin/rewards/analytics'
      preLoaderRoute: typeof AuthenticatedAdminRewardsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRewardsRouteRoute
    }
  }
}

interface AuthenticatedAdminRewardsRouteRouteChildren {
  AuthenticatedAdminRewardsAnalyticsRoute: typeof AuthenticatedAdminRewardsAnalyticsRoute
  AuthenticatedAdminRewardsAuditRoute: typeof AuthenticatedAdminRewardsAuditRoute
  AuthenticatedAdminRewardsReferralsRoute: typeof AuthenticatedAdminRewardsReferralsRoute
  AuthenticatedAdminRewardsWheelsRoute: typeof AuthenticatedAdminRewardsWheelsRoute
  AuthenticatedAdminRewardsIndexRoute: typeof AuthenticatedAdminRewardsIndexRoute
}

const AuthenticatedAdminRewardsRouteRouteChildren: AuthenticatedAdminRewardsRouteRouteChildren =
  {
    AuthenticatedAdminRewardsAnalyticsRoute:
      AuthenticatedAdminRewardsAnalyticsRoute,
    AuthenticatedAdminRewardsAuditRoute: AuthenticatedAdminRewardsAuditRoute,
    AuthenticatedAdminRewardsReferralsRoute:
      AuthenticatedAdminRewardsReferralsRoute,
    AuthenticatedAdminRewardsWheelsRoute: AuthenticatedAdminRewardsWheelsRoute,
    AuthenticatedAdminRewardsIndexRoute: AuthenticatedAdminRewardsIndexRoute,
  }

const AuthenticatedAdminRewardsRouteRouteWithChildren =
  AuthenticatedAdminRewardsRouteRoute._addFileChildren(
    AuthenticatedAdminRewardsRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminRewardsRouteRoute: typeof AuthenticatedAdminRewardsRouteRouteWithChildren
  AuthenticatedAdminAbuseRoute: typeof AuthenticatedAdminAbuseRoute
  AuthenticatedAdminCampaignsRoute: typeof AuthenticatedAdminCampaignsRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminDeliveryRoute: typeof AuthenticatedAdminDeliveryRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPromotionsRoute: typeof AuthenticatedAdminPromotionsRoute
  AuthenticatedAdminSellersRoute: typeof AuthenticatedAdminSellersRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminRewardsRouteRoute:
      AuthenticatedAdminRewardsRouteRouteWithChildren,
    AuthenticatedAdminAbuseRoute: AuthenticatedAdminAbuseRoute,
    AuthenticatedAdminCampaignsRoute: AuthenticatedAdminCampaignsRoute,
    AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
    AuthenticatedAdminDeliveryRoute: AuthenticatedAdminDeliveryRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminPromotionsRoute: AuthenticatedAdminPromotionsRoute,
    AuthenticatedAdminSellersRoute: AuthenticatedAdminSellersRoute,
    AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSellerRouteRouteChildren {
  AuthenticatedSellerAnalyticsRoute: typeof AuthenticatedSellerAnalyticsRoute
  AuthenticatedSellerCampaignsRoute: typeof AuthenticatedSellerCampaignsRoute
  AuthenticatedSellerCouponsRoute: typeof AuthenticatedSellerCouponsRoute
  AuthenticatedSellerDeliveryRoute: typeof AuthenticatedSellerDeliveryRoute
  AuthenticatedSellerDishesRoute: typeof AuthenticatedSellerDishesRoute
  AuthenticatedSellerMealPlansRoute: typeof AuthenticatedSellerMealPlansRoute
  AuthenticatedSellerOrdersRoute: typeof AuthenticatedSellerOrdersRoute
  AuthenticatedSellerSubscriptionsRoute: typeof AuthenticatedSellerSubscriptionsRoute
  AuthenticatedSellerIndexRoute: typeof AuthenticatedSellerIndexRoute
}

const AuthenticatedSellerRouteRouteChildren: AuthenticatedSellerRouteRouteChildren =
  {
    AuthenticatedSellerAnalyticsRoute: AuthenticatedSellerAnalyticsRoute,
    AuthenticatedSellerCampaignsRoute: AuthenticatedSellerCampaignsRoute,
    AuthenticatedSellerCouponsRoute: AuthenticatedSellerCouponsRoute,
    AuthenticatedSellerDeliveryRoute: AuthenticatedSellerDeliveryRoute,
    AuthenticatedSellerDishesRoute: AuthenticatedSellerDishesRoute,
    AuthenticatedSellerMealPlansRoute: AuthenticatedSellerMealPlansRoute,
    AuthenticatedSellerOrdersRoute: AuthenticatedSellerOrdersRoute,
    AuthenticatedSellerSubscriptionsRoute:
      AuthenticatedSellerSubscriptionsRoute,
    AuthenticatedSellerIndexRoute: AuthenticatedSellerIndexRoute,
  }

const AuthenticatedSellerRouteRouteWithChildren =
  AuthenticatedSellerRouteRoute._addFileChildren(
    AuthenticatedSellerRouteRouteChildren,
  )

interface AuthenticatedDeliveryRouteChildren {
  AuthenticatedDeliveryRegisterRoute: typeof AuthenticatedDeliveryRegisterRoute
  AuthenticatedDeliveryIndexRoute: typeof AuthenticatedDeliveryIndexRoute
}

const AuthenticatedDeliveryRouteChildren: AuthenticatedDeliveryRouteChildren = {
  AuthenticatedDeliveryRegisterRoute: AuthenticatedDeliveryRegisterRoute,
  AuthenticatedDeliveryIndexRoute: AuthenticatedDeliveryIndexRoute,
}

const AuthenticatedDeliveryRouteWithChildren =
  AuthenticatedDeliveryRoute._addFileChildren(
    AuthenticatedDeliveryRouteChildren,
  )

interface AuthenticatedMySubscriptionsRouteChildren {
  AuthenticatedMySubscriptionsIdRoute: typeof AuthenticatedMySubscriptionsIdRoute
}

const AuthenticatedMySubscriptionsRouteChildren: AuthenticatedMySubscriptionsRouteChildren =
  {
    AuthenticatedMySubscriptionsIdRoute: AuthenticatedMySubscriptionsIdRoute,
  }

const AuthenticatedMySubscriptionsRouteWithChildren =
  AuthenticatedMySubscriptionsRoute._addFileChildren(
    AuthenticatedMySubscriptionsRouteChildren,
  )

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedSellerRouteRoute: typeof AuthenticatedSellerRouteRouteWithChildren
  AuthenticatedAddressesRoute: typeof AuthenticatedAddressesRoute
  AuthenticatedBecomeSellerRoute: typeof AuthenticatedBecomeSellerRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedDeliveryRoute: typeof AuthenticatedDeliveryRouteWithChildren
  AuthenticatedMySubscriptionsRoute: typeof AuthenticatedMySubscriptionsRouteWithChildren
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedSellerRouteRoute: AuthenticatedSellerRouteRouteWithChildren,
  AuthenticatedAddressesRoute: AuthenticatedAddressesRoute,
  AuthenticatedBecomeSellerRoute: AuthenticatedBecomeSellerRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedDeliveryRoute: AuthenticatedDeliveryRouteWithChildren,
  AuthenticatedMySubscriptionsRoute:
    AuthenticatedMySubscriptionsRouteWithChildren,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MealPlansRouteChildren {
  MealPlansIdRoute: typeof MealPlansIdRoute
}

const MealPlansRouteChildren: MealPlansRouteChildren = {
  MealPlansIdRoute: MealPlansIdRoute,
}

const MealPlansRouteWithChildren = MealPlansRoute._addFileChildren(
  MealPlansRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  CartRoute: CartRoute,
  MealPlansRoute: MealPlansRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  DishIdRoute: DishIdRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
